package com.example.funnyproverbquestion;

public class Proverbs {
    public String[] turkishProverbs = {
            "Damlaya damlaya göl olur",
            "Ağaç yaşken eğilir",
            "Bir elin nesi var, iki elin sesi var",
            "Sabır acıdır, meyvesi tatlıdır",
            "Taşıma suyla değirmen dönmez",
            "Az veren candan, çok veren maldan",
            "Damdan düşenin halinden damdan düşen anlar",
            "Gülü seven dikenine katlanır",
            "Akıl akıldan üstündür",
            "Borç yiğidin kamçısıdır",
            "Dert paylaşıldıkça azalır",
            "Gözden uzak olan gönülden de uzak olur",
            "Hak yerini bulur",
            "Rüzgar eken fırtına biçer",
            "Tatlı dil yılanı deliğinden çıkarır",
            "Ucuz etin yahnisi yavan olur",
            "Varlık içinde darlık",
            "Zararın neresinden dönülse kardır",
            "Aslan yattığı yerden belli olur",
            "Can çıkmayınca huy çıkmaz",
            "İyi dost kara günde belli olur",
            "Bir lisan, bir insan; iki lisan, iki insan",
            "Sabah ola, hayır ola",
            "Su testisi su yolunda kırılır",
            "Yatan aslandan koşan tilki yeğdir",
            "Ateş olmayan yerden duman çıkmaz",
            "Balık baştan kokar",
            "Düşenin dostu olmaz",
            "Gülme komşuna, gelir başına",
            "Her şeyin yenisi, dostun eskisi makbuldür.",
            "Mart kapıdan baktırır, kazma kürek yaktırır",
            "Nerede birlik, orada dirlik",
            "Olmayacak duaya amin denmez",
            "Para parayı çeker",
            "Yaş kesen başı keser",
            "Zenginin malı, züğürdün çenesini yorar",
            "Açık ağız aç kalmaz",
            "Küçük suda büyük balık olmaz",
            "Bir musibet bin nasihatten iyidir",
            "Güneş balçıkla sıvanmaz",
            "Üzüm üzüme baka baka kararır",
            "Taş yerinde ağırdır",
            "Kaz gelen yerden tavuk esirgenmez",
            "Kedi uzanamadığı ciğerine mundar der",
            "Ayağını yorganına göre uzat",
    };
}
